### ISSUE TITLE
Output doesn't include chain of requests and responses

### ISSUE THREAD

**Issue by mariandppb** [surface-security/httpx#23]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the provider and it is still present.

### Related software versions.

httpx 1.2.6

### Affected resource(s)

json output

### Link to debug output

no

### Expected output

The output should include smth like this:

```
"chain": {
         "request" :  "",
         "response" : "",
}
```

with the request and response containing http headers like user-agent, cookies etc.

### Actual output

Does not include the chain.

### Steps to reproduce

Tested the image locally:
1. built the latest image locally 
2. loaded it in the local rootbox
3. started the scanner from the surface UI
4. checked the output files with grep

### Additional factoids

I tried also with the `-include-chain` arg but still there was no chain.

### **FYI**
Last week i tried forking the latest projectdiscovery version of httpx and building it locally.
The output was a single file containing all the JSON outputs from all the scans, but they all contained the chain of requests.

**Comment by mariandppb** [comment]
Hey @fopina , do you have any idea/explication about what is happening ^^ ?

**Comment by fopina** [comment]
I think that was something we had fixed in our fork already actually.
Have you reproduced it with the "new" 1.12 version? The one made out of the new git tree but before merging the update to 1.26

Just to bisect when it "went away"

**Comment by fopina** [comment]
@mariandppb we have each release tagged.
14 is the last one before the "tree reset", you can use that one in surface (in the scanner config) instead of latest.

15 is the one with version 1.12 after tree reset, has it lost chain info as well?

**Comment by mariandppb** [comment]
hey @fopina 
I just tested version 14  but i don't see any chain info in the output in this version either, but i do see a lot of "ERROR: The request could not be satisfied" in the title field from the output so i don't know if this has smth to do with the lack of chain info

**Comment by fopina** [comment]
@mariandppb so at least it’s not related to the (tree) change

I don’t remember using that chain info so I can’t really add anything to it. Just wanted to make sure it wasn’t something there before that I broke :)

**Comment by mariandppb** [comment]
yes, most likely there was nothing broken :))) 
sorry for the scare!
however, i'll look into why there isn't any chain info output because when i tested with the upstream version (not this fork) there was the chain and i made the parser around that version
maybe we could get rid of the fork ¯\_(ツ)_/¯
